---
title: "Corrected Albert Comparison v2"
author: "Nel Marín"
date: "20/6/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Import mapping files

```{r Files, echo=FALSE}

#Set the working directory
setwd("~/PracticasIBMB/12_Corrected_results")

#Load the TSV file using read.delim()
dataframe_complete <- read.delim("~/PracticasIBMB/5_TEs_mapping_&_repeat_analysis/thedataframe_complete.tsv", header = FALSE, stringsAsFactors = FALSE)

#Change the column names
colnames(dataframe_complete) <- c("seqname", "source", "feature", "start", "end",
                                  "score", "strand", "frame", "class", "family",
                                  "group", "H1.0", "H1.2",  "H1.3", "H1.4", "H1.5",
                                  "H1X","H3K9me3_SRR12349402", "K27me3",
                                  "K9me3_AJV7", "K9me3_AJV84X")

```

## 2. Create the actual dataframe

```{r Dataframe}

#Remove the H3K9me3 columns that we are not using
new_dataframe_complete <- dataframe_complete[, c(1:19)]

#New name for the H3K9me3 sample
colnames(new_dataframe_complete)[18] <- "K9me3"

#Identify numeric columns
numeric_cols <- sapply(new_dataframe_complete, is.numeric)

#Change "start", "end" & "score" to FALSE (not numeric)
numeric_cols[4:6] <- FALSE

#Filter the dataframe
new_filtered_dataframe_complete <- new_dataframe_complete[rowSums(new_dataframe_complete[, numeric_cols] != 0) > 0, ]
rownames(new_filtered_dataframe_complete) <- seq(1:nrow(new_filtered_dataframe_complete))

```

## 3. Construct the summary dataframe

```{r New dataframe}

#Reduce the original dataframe
tax_df <- new_filtered_dataframe_complete[, c(9, 10)]

#Create the summary dataframe (similar to the excel one)
summary_df <- unique(tax_df)

#Order the unique rows based on the class and family
summary_df <- summary_df[order(summary_df$family), ]

#New rownames
rownames(summary_df) <- seq(1, nrow(summary_df))

```

## 4. Calculate the counts and percentage (already done)

```{r Counts}

########################################################### COUNTS
#Get the counts for each family
family_counts <- as.data.frame(table(tax_df$family))
#Change the names of the columns
colnames(family_counts) <- c("family", "counts")
#Check that the families are in the same order
#summary_df$counts <- family_counts$counts
#Append to the summary_df
summary_df$counts <- family_counts$counts

########################################################### PERCENTAGES
#Calculate the percentages for each family
summary_df$percentage <- round(100*summary_df$count/sum(summary_df$count), 
                               digits = 2)

########################################################### ORDER
#Reorder to copy to excel
summary_df <- summary_df[order(summary_df$class, summary_df$family), ]
rownames(summary_df) <- seq(1, nrow(summary_df))
#Save the table to copy to excel
#write.table(summary_df, "table.tsv", sep = "\t")

```

## 5. Calculate the occupancy and percentage

```{r Occupancy}

#Set the genome length (calculated in excel)
genome_length <- 3117292070
#Subset a new dataframe with the start and end coordinates
coord_df <- new_filtered_dataframe_complete[, c(4, 5, 9, 10)]
#Create a new column with the length of each repeat
coord_df$length <- coord_df$end - coord_df$start

########################################################### OCCUPANCY
# Calculate the sum of length for each family in coord_df
family_lengths <- tapply(coord_df$length, coord_df$family, sum)  
# Add the sum of lengths as a new column in summary_df
summary_df$length <- family_lengths[match(summary_df$family, 
                                          names(family_lengths))]

########################################################### PERCENTAGES
#Calculate the percentages for each family
summary_df$percentage_length <- round(100*summary_df$length/genome_length, 
                                      digits = 2)
#Save the table to copy to excel
#write.table(summary_df, "table.tsv", sep = "\t")

```

## 6. Get the repeat counts for each family

```{r Repeat counts}

#Reduce the original dataframe
df_tax <- new_filtered_dataframe_complete[, c(9, 10, 11)]

#Get the unique class categories
classes <- sort(unique(df_tax$class))

#Get the unique family categories
families <- sort(unique(df_tax$family))

#Create an empty dataframe to store the count results
family_summary <- data.frame(family = character(), 
                             n_repeats = numeric(), 
                             stringsAsFactors = FALSE)

#Create one dataframe per family
for (category in families) {
  #Subset the dataframe for the current category
  df_category <- subset(df_tax, family == category)
  assign(paste0("df_", category), df_category)
  #Get the number of rows in the dataframe
  row_count <- nrow(df_category)
  # Add the category and row count to the result dataframe
  family_summary <- rbind(family_summary, data.frame(family = category,
                                                     n_repeats = row_count,
                                                     stringsAsFactors = FALSE))
}

#Remove the temporal "df_category" variable
rm(df_category)

#Loop through the dataframes
for (i in 1:length(families)) {
  #Create a variable that temporarily stores each dataframe
  temp_df <- get(paste0("df_", families[i]))
  #Create an empty dataframe to store the results
  temp_result_df <- data.frame(group = character(), 
                               count = integer(), 
                               stringsAsFactors = FALSE)
  #Calculate the counts for each group in the dataframe
  counts <- aggregate(temp_df$group, 
                      by = list(class = temp_df$class, 
                                family = temp_df$family, 
                                group = temp_df$group), 
                      FUN = length)
  #Rename the columns of the counts dataframe
  colnames(counts) <- c("class", "family", "group", "count")
  #Add the counts to the result dataframe
  temp_result_df <- rbind(temp_result_df, counts)
  #Order the groups from the least appearences to the most
  temp_result_df <- temp_result_df[order(temp_result_df$count), ]
  #Change rownames
  rownames(temp_result_df) <- seq(1, nrow(temp_result_df))
  #Levels and factors
  levels(temp_result_df$group) <- temp_result_df$group
  #Change the name of the dataframe
  assign(paste0("df_count_", families[i]), temp_result_df)
}

#Remove the temporal "df_category" variable
rm(temp_df)
rm(temp_result_df)

```

## 7. Merge all df_count dataframes

```{r Merge}

#Get the data frame names with a common prefix "df"
names_df_count <- ls(pattern = "^df_count_")

#Merge data frames as rows
merged_df <- do.call(rbind, lapply(names_df_count, get))

```
